### ISSUE TITLE
Out of Bounds Geotiff

### ISSUE THREAD

**Issue by vagupta16** [tilemill-project/tilemill#2027]
I'm trying to add a GeoTiff to TileMill. The GeoTiff was georeferenced in WGS84 using ArcMap 10.0. However, when I attempt to bring the file into TileMill, specifying that the spatial reference system is WGS84, I receive the following message: 

"Detected out of bounds geographic extent
(-180, 6705420.48214243, 180, 85.051) for layer 'rumsey11'. Please ensure that the SRS for this layer is correct. Its native extent is '-23721.528040795725, 6705420.48214243, 1116.7829325636303, 6720068.970914153'

**Comment by geosam** [comment]
Hello! 

I have basically the same problem (see error message pasted below) but I don't think its because of a problem with the projection. It must be a problem with Tile Mill. The raster image was created in ArcGIS from a map using the export function (to TIFF with georeferencing). The source map document projection was British National Grid (OSGB36) but I used the 'project' tool to reproject the raster to WGS84 Web Mercator ESPG 3857. It is definitely now in this projection. I even tried clipping the raster to make sure it was within reasonable bounds. I also compared the bounds displayed by the Tile Mill error message with the desired bounds of my map export raster image using the cursor position indicator displayed in metres in the bottom right corner of the ArcGIS window and they are the same. (I even tried using Gdal but this failed too). 

"Detected out of bounds geographic extent (-180,7409525.600717108,-461356.86595747736,85.051) for layer 'samarcexp1projwm2'. Please ensure that the SRS for this layer is correct. Its native extent is '-468498.16288162104,7409525.600717108,-461356.86595747736,7413921.926176425"
