### ISSUE TITLE
How to enable osm.input plugin?

### ISSUE THREAD

**Issue by csytsma** [tilemill-project/tilemill#2573]
When running from latest source (Version 0.10.2 (v0.10.1-395-gff87d20)) , using .osm files as a layer is not supported, which it is under 0.10.1 packaged versions for MacOS.

1) Can this be re-enabled? Why was it removed? Is it a Mapnik issue?

2) Alternatively, I've tried to include the osm.input in my local source, but when running I get the following error:

```
Problem loading plugin library: /Users/xxx/Development/Tilemill/tilemill/node_modules/mapnik/lib/binding/node-v46-darwin-x64/mapnik/input/osm.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
```

I can't figure out how to satisfy the osm.input plugin dependency.

Thanks in advance.

**Comment by csytsma** [comment]
Does anyone know why this plugin was removed? Can it easily be added back?

**Comment by pnorman** [comment]
You'll need to build node-mapnik against a version of mapnik that has the OSM plugin built, and use the `--build-from-source` flag when installing with `npm`.

When you just do `npm install` it downloads a binary blob from Mapbox for `node-mapnik`, which has whatever they compiled it with.

I would also suggest not using the OSM plugin, because it doesn't work well, work with large files, handle multipolygons correctly, or get much use.
